pipeline {
    agent any
    
    triggers {
        pollSCM('* * * * *') // Poll SCM for changes every minute
    }
    
    environment {
        // Specify the Python version or path if necessary
        PYTHON_ENV = 'python3'
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', credentialsId: 'github-credentials-id', url: 'https://github.com/Ishaan762/PES1UG21CS240-DevOps-1.git'
            }
        }
        
        stage('Setup Environment') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install -r requirements.txt'
            }
        }
        
        stage('Run Tests') {
            steps {
                sh '. venv/bin/activate && pytest --junitxml=report.xml'
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'report.xml', allowEmptyArchive: true
            junit 'report.xml'
        }
    }
}
